/**
 * Used when working with this plugin.
 */
plugins {
	id "groovy-gradle-plugin"
	id "se.bjurr.gradle.bundle-jar"
}

/**
 * Dependencies needed by the plugin in src/main/groovy
 */
dependencies {
	implementation "com.github.ben-manes:gradle-versions-plugin:0.54.0"

	testImplementation gradleTestKit()
	testImplementation platform("org.junit:junit-bom:6.1.3")
	testImplementation "org.junit.jupiter:junit-jupiter"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
	testImplementation "org.assertj:assertj-core:3.27.7"
}

javaExtension {
	javaVersion = 17
}

test {
	useJUnitPlatform()
}
